export const DB = [
  {
    img: "https://links.papareact.com/xqj",
    type: "Private room",
    location: "London",
    desc: "Stay at this spacious Edwardian House",
    detail: ["1 guest", "1 bedroom", "1 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen", "Free parking", "Washing Machine"],
    star: 4.73,
    totalReviews: 112,
    price: "£30",
    total: "£117 total",
    long: -0.0022275,
    lat: 51.5421655,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
  {
    img: "https://links.papareact.com/uz7",
    type: "Private room",
    location: "London",
    desc: "London Studio Apartments",
    detail: ["1 guest", "1 bedroom", "1 bed", "1 bathrooms"],
    feature: ["Free parking", "Washing Machine"],
    star: 3.8,
    totalReviews: 32,
    price: "£35",
    total: "£207 total",
    long: -0.135638,
    lat: 51.521916,
  },
  {
    img: "https://links.papareact.com/6as",
    type: "Private room",
    location: "London",
    desc: "30 mins to Oxford Street, Excel London",
    detail: ["4 guest", "2 bedroom", "3 bed", "2 bathrooms"],
    feature: ["Wifi", "Washing Machine"],
    star: 4.1,
    totalReviews: 14,
    price: "£55",
    total: "£320 total",
    long: -0.069961,
    lat: 51.472618,
  },
  {
    img: "https://links.papareact.com/xhc",
    type: "Private room",
    location: "London",
    desc: "Spacious Peaceful Modern Bedroom",
    detail: ["5 guest", "3 bedroom", "3 bed", "2 shared bathrooms"],
    feature: ["Wifi", "Free parking", "Washing Machine"],
    star: 5.0,
    totalReviews: 32,
    price: "£60",
    total: "£450 total",
    long: -0.08472,
    lat: 51.510794,
  },
  {
    img: "https://links.papareact.com/pro",
    type: "Private room",
    location: "London",
    desc: "The Blue Room In London",
    detail: ["3 guest", "2 bedroom", "2 bed"],
    feature: ["Wifi", "Kitchen", "Free parking"],
    star: 4.23,
    totalReviews: 52,
    price: "£65",
    total: "£480 total",
    long: -0.094116,
    lat: 51.51401,
  },
  {
    img: "https://links.papareact.com/8w2",
    type: "Private room",
    location: "London",
    desc: "5 Star Luxury Apartment",
    detail: ["2 guest", "1 bedroom", "1 bed", "1 bathrooms"],
    feature: ["Wifi", "Kitchen", "Free parking", "Washing Machine"],
    star: 3.85,
    totalReviews: 22,
    price: "£90",
    total: "£650 total",
    long: -0.109889,
    lat: 51.521245,
  },
  {
    img: "https://links.papareact.com/xqj",
    type: "Private room",
    location: "London",
    desc: "Stay at this spacious Edwardian House",
    detail: ["1 guest", "1 bedroom", "1 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen", "Free parking", "Washing Machine"],
    star: 4.73,
    totalReviews: 112,
    price: "£30",
    total: "£117 total",
    long: -0.0022275,
    lat: 51.5421655,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
  {
    img: "https://links.papareact.com/xqj",
    type: "Private room",
    location: "London",
    desc: "Stay at this spacious Edwardian House",
    detail: ["1 guest", "1 bedroom", "1 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen", "Free parking", "Washing Machine"],
    star: 4.73,
    totalReviews: 112,
    price: "£30",
    total: "£117 total",
    long: -0.0022275,
    lat: 51.5421655,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
  {
    img: "https://links.papareact.com/uz7",
    type: "Private room",
    location: "London",
    desc: "London Studio Apartments",
    detail: ["1 guest", "1 bedroom", "1 bed", "1 bathrooms"],
    feature: ["Free parking", "Washing Machine"],
    star: 3.8,
    totalReviews: 32,
    price: "£35",
    total: "£207 total",
    long: -0.135638,
    lat: 51.521916,
  },
  {
    img: "https://links.papareact.com/6as",
    type: "Private room",
    location: "London",
    desc: "30 mins to Oxford Street, Excel London",
    detail: ["4 guest", "2 bedroom", "3 bed", "2 bathrooms"],
    feature: ["Wifi", "Washing Machine"],
    star: 4.1,
    totalReviews: 14,
    price: "£55",
    total: "£320 total",
    long: -0.069961,
    lat: 51.472618,
  },
  {
    img: "https://links.papareact.com/xhc",
    type: "Private room",
    location: "London",
    desc: "Spacious Peaceful Modern Bedroom",
    detail: ["5 guest", "3 bedroom", "3 bed", "2 shared bathrooms"],
    feature: ["Wifi", "Free parking", "Washing Machine"],
    star: 5.0,
    totalReviews: 32,
    price: "£60",
    total: "£450 total",
    long: -0.08472,
    lat: 51.510794,
  },
  {
    img: "https://links.papareact.com/pro",
    type: "Private room",
    location: "London",
    desc: "The Blue Room In London",
    detail: ["3 guest", "2 bedroom", "2 bed"],
    feature: ["Wifi", "Kitchen", "Free parking"],
    star: 4.23,
    totalReviews: 52,
    price: "£65",
    total: "£480 total",
    long: -0.094116,
    lat: 51.51401,
  },
  {
    img: "https://links.papareact.com/8w2",
    type: "Private room",
    location: "London",
    desc: "5 Star Luxury Apartment",
    detail: ["2 guest", "1 bedroom", "1 bed", "1 bathrooms"],
    feature: ["Wifi", "Kitchen", "Free parking", "Washing Machine"],
    star: 3.85,
    totalReviews: 22,
    price: "£90",
    total: "£650 total",
    long: -0.109889,
    lat: 51.521245,
  },
  {
    img: "https://links.papareact.com/xqj",
    type: "Private room",
    location: "London",
    desc: "Stay at this spacious Edwardian House",
    detail: ["1 guest", "1 bedroom", "1 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen", "Free parking", "Washing Machine"],
    star: 4.73,
    totalReviews: 112,
    price: "£30",
    total: "£117 total",
    long: -0.0022275,
    lat: 51.5421655,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
  {
    img: "https://links.papareact.com/xqj",
    type: "Private room",
    location: "London",
    desc: "Stay at this spacious Edwardian House",
    detail: ["1 guest", "1 bedroom", "1 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen", "Free parking", "Washing Machine"],
    star: 4.73,
    totalReviews: 112,
    price: "£30",
    total: "£117 total",
    long: -0.0022275,
    lat: 51.5421655,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
  {
    img: "https://links.papareact.com/uz7",
    type: "Private room",
    location: "London",
    desc: "London Studio Apartments",
    detail: ["1 guest", "1 bedroom", "1 bed", "1 bathrooms"],
    feature: ["Free parking", "Washing Machine"],
    star: 3.8,
    totalReviews: 32,
    price: "£35",
    total: "£207 total",
    long: -0.135638,
    lat: 51.521916,
  },
  {
    img: "https://links.papareact.com/6as",
    type: "Private room",
    location: "London",
    desc: "30 mins to Oxford Street, Excel London",
    detail: ["4 guest", "2 bedroom", "3 bed", "2 bathrooms"],
    feature: ["Wifi", "Washing Machine"],
    star: 4.1,
    totalReviews: 14,
    price: "£55",
    total: "£320 total",
    long: -0.069961,
    lat: 51.472618,
  },
  {
    img: "https://links.papareact.com/xhc",
    type: "Private room",
    location: "London",
    desc: "Spacious Peaceful Modern Bedroom",
    detail: ["5 guest", "3 bedroom", "3 bed", "2 shared bathrooms"],
    feature: ["Wifi", "Free parking", "Washing Machine"],
    star: 5.0,
    totalReviews: 32,
    price: "£60",
    total: "£450 total",
    long: -0.08472,
    lat: 51.510794,
  },
  {
    img: "https://links.papareact.com/pro",
    type: "Private room",
    location: "London",
    desc: "The Blue Room In London",
    detail: ["3 guest", "2 bedroom", "2 bed"],
    feature: ["Wifi", "Kitchen", "Free parking"],
    star: 4.23,
    totalReviews: 52,
    price: "£65",
    total: "£480 total",
    long: -0.094116,
    lat: 51.51401,
  },
  {
    img: "https://links.papareact.com/8w2",
    type: "Private room",
    location: "London",
    desc: "5 Star Luxury Apartment",
    detail: ["2 guest", "1 bedroom", "1 bed", "1 bathrooms"],
    feature: ["Wifi", "Kitchen", "Free parking", "Washing Machine"],
    star: 3.85,
    totalReviews: 22,
    price: "£90",
    total: "£650 total",
    long: -0.109889,
    lat: 51.521245,
  },
  {
    img: "https://links.papareact.com/xqj",
    type: "Private room",
    location: "London",
    desc: "Stay at this spacious Edwardian House",
    detail: ["1 guest", "1 bedroom", "1 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen", "Free parking", "Washing Machine"],
    star: 4.73,
    totalReviews: 112,
    price: "£30",
    total: "£117 total",
    long: -0.0022275,
    lat: 51.5421655,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
  {
    img: "https://links.papareact.com/xqj",
    type: "Private room",
    location: "London",
    desc: "Stay at this spacious Edwardian House",
    detail: ["1 guest", "1 bedroom", "1 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen", "Free parking", "Washing Machine"],
    star: 4.73,
    totalReviews: 112,
    price: "£30",
    total: "£117 total",
    long: -0.0022275,
    lat: 51.5421655,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
  {
    img: "https://links.papareact.com/uz7",
    type: "Private room",
    location: "London",
    desc: "London Studio Apartments",
    detail: ["1 guest", "1 bedroom", "1 bed", "1 bathrooms"],
    feature: ["Free parking", "Washing Machine"],
    star: 3.8,
    totalReviews: 32,
    price: "£35",
    total: "£207 total",
    long: -0.135638,
    lat: 51.521916,
  },
  {
    img: "https://links.papareact.com/6as",
    type: "Private room",
    location: "London",
    desc: "30 mins to Oxford Street, Excel London",
    detail: ["4 guest", "2 bedroom", "3 bed", "2 bathrooms"],
    feature: ["Wifi", "Washing Machine"],
    star: 4.1,
    totalReviews: 14,
    price: "£55",
    total: "£320 total",
    long: -0.069961,
    lat: 51.472618,
  },
  {
    img: "https://links.papareact.com/xhc",
    type: "Private room",
    location: "London",
    desc: "Spacious Peaceful Modern Bedroom",
    detail: ["5 guest", "3 bedroom", "3 bed", "2 shared bathrooms"],
    feature: ["Wifi", "Free parking", "Washing Machine"],
    star: 5.0,
    totalReviews: 32,
    price: "£60",
    total: "£450 total",
    long: -0.08472,
    lat: 51.510794,
  },
  {
    img: "https://links.papareact.com/pro",
    type: "Private room",
    location: "London",
    desc: "The Blue Room In London",
    detail: ["3 guest", "2 bedroom", "2 bed"],
    feature: ["Wifi", "Kitchen", "Free parking"],
    star: 4.23,
    totalReviews: 52,
    price: "£65",
    total: "£480 total",
    long: -0.094116,
    lat: 51.51401,
  },
  {
    img: "https://links.papareact.com/8w2",
    type: "Private room",
    location: "London",
    desc: "5 Star Luxury Apartment",
    detail: ["2 guest", "1 bedroom", "1 bed", "1 bathrooms"],
    feature: ["Wifi", "Kitchen", "Free parking", "Washing Machine"],
    star: 3.85,
    totalReviews: 22,
    price: "£90",
    total: "£650 total",
    long: -0.109889,
    lat: 51.521245,
  },
  {
    img: "https://links.papareact.com/xqj",
    type: "Private room",
    location: "London",
    desc: "Stay at this spacious Edwardian House",
    detail: ["1 guest", "1 bedroom", "1 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen", "Free parking", "Washing Machine"],
    star: 4.73,
    totalReviews: 112,
    price: "£30",
    total: "£117 total",
    long: -0.0022275,
    lat: 51.5421655,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
  {
    img: "https://links.papareact.com/hz2",
    type: "Private room",
    location: "London",
    desc: "Independant luxury studio apartment",
    detail: ["2 guest", "2 bedroom", "2 bed", "1.5 shared bathrooms"],
    feature: ["Wifi", "Kitchen"],
    star: 4.3,
    totalReviews: 12,
    price: "£40",
    total: "£157 total",
    long: -0.095091,
    lat: 51.48695,
  },
];
